quick-fix
KeyError: 'files' on line 661
 - replaced calling it by [] and use get(key, default) with default being None
 - amended to be PEP8 compliant

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int' on line 562
 - caused by forgetting to lowercase network in line 560